### ISSUE TITLE
Shutoff button

### ISSUE THREAD

**Issue by Sedaxel** [mikeoliphant/Stompbox#1]
It would be great to have a shutoff button somewhere in the UI.

This way you wouldn't need to access the Pi to shut it off (keyboard+display, SSH or whatever).

Maybe, the button should not be very accessible, in order to avoid an accidental shutoff. If it's hidden in some menu, it would be safe.

**Comment by mikeoliphant** [comment]
This should be possible. Bear in mind, though, that it will only work if you are running stompbox as root. Otherwise it won't have permissions to issue a shutdown.

**Comment by mikeoliphant** [comment]
I've replaced the "PB" button with a little options menu that allows you to switch interface type, and also adds a shutdown option.

**Comment by Sedaxel** [comment]
Mike, it works perfectly. Thank you so much!

**Comment by mikeoliphant** [comment]
👍

**Comment by mikeoliphant** [comment]
Btw, if you are in Pedalboard view, you can double-tap the screen to bring up the interface/shutdown menu.
